lib: update open-amp lib to release v2023.04.0
zephyrproject-rtos/open-amp pull request #15
Opened 2023-05-19 08:18 UTC by carlocaione

Origin:
	https://github.com/OpenAMP/open-amp

Commit:
	accac4d3610cbb268f3c3fe3c31dc45dd4c4dd17

Status:
	Merge open-amp new version after removing the apps dir

Release description:
	https://github.com/OpenAMP/open-amp/releases/tag/v2023.04.0

2023-05-19 08:26 UTC, gmarull approved these changes

2023-05-19 10:33 UTC, hubertmis approved these changes

2023-05-22 07:55 UTC, arnopo requested changes
Hi @carlocaion, 
I can see 2 updates missings to be aligned:
- the folder `docs` as been moved to `doc` and updated
- would be nice to add the `Doxyfile` file.

2023-05-22 09:27 UTC, arnopo approved these changes
LGTM, thanks!

2023-05-22 09:54 UTC, merged