lib: update open-amp lib to release v2023.10.0
zephyrproject-rtos/open-amp pull request #18
Opened 2023-11-21 14:17 UTC by arnopo

Origin:
    	https://github.com/OpenAMP/open-amp

Commit:
    	1904dee18da85400e72b8f55c5c99e872a486573

Status:
  	Merge open-amp new version after removing the apps and scripts
  	directories.

Release description:
    	https://github.com/OpenAMP/open-amp/releases/tag/v2023.10.0

2023-11-22 10:11 UTC, carlocaione approved these changes

2023-11-22 10:38 UTC, carlescufi requested changes
There are test failures in the integration PR.

2023-12-14 16:17 UTC, arnopo commented
> There are test failures in the integration PR.

Solved

2023-12-14 18:36 UTC, carlescufi approved these changes

2023-12-14 18:36 UTC, merged